### ISSUE TITLE
Problem identifing image

### ISSUE THREAD

**Issue by Fale** [mattharrison/rst2odp#35]
I've downloaded the intro.rst file and the img/text.png, but when I try to execute rst2odt against it, this is the result:

````
[fale@redhat 00_work_needed]$ rst2odp --traceback intro.rst intro.odp
Traceback (most recent call last):
  File "/usr/bin/rst2odp", line 1308, in <module>
    sys.exit(main(sys.argv) or 0)
  File "/usr/bin/rst2odp", line 1297, in main
    enable_exit_status=enable_exit_status)
  File "/usr/lib/python3.5/site-packages/docutils/core.py", line 219, in publish
    output = self.writer.write(self.document, self.destination)
  File "/usr/lib/python3.5/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/bin/rst2odp", line 211, in translate
    self.document.walkabout(self.visitor)
  File "/usr/lib/python3.5/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.5/site-packages/docutils/nodes.py", line 174, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.5/site-packages/docutils/nodes.py", line 166, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/bin/rst2odp", line 294, in dispatch_visit
    nodes.GenericNodeVisitor.dispatch_visit(self, node)
  File "/usr/lib/python3.5/site-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/usr/lib/python3.5/site-packages/odplib/preso.py", line 104, in wrapper
    data = func(*args, **kw)
  File "/usr/bin/rst2odp", line 940, in visit_image
    p = preso.Picture(os.path.abspath(source), **node.attributes)
  File "/usr/lib/python3.5/site-packages/odplib/preso.py", line 580, in __init__
    image = Image.open(filepath)
  File "/usr/lib64/python3.5/site-packages/PIL/Image.py", line 2309, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/home/fale/Fedora/00_work_needed/img/test.png'
````

The image is where it's searched
````
[fale@redhat 00_work_needed]$ pwd
/home/fale/Fedora/00_work_needed
[fale@redhat 00_work_needed]$ ls img/
test.png
````

Additional info:
````
[fale@redhat 00_work_needed]$ python3 --version
Python 3.5.1
[fale@redhat 00_work_needed]$ cat /etc/os-release 
NAME=Fedora
VERSION="24 (Workstation Edition)"
ID=fedora
VERSION_ID=24
PRETTY_NAME="Fedora 24 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:24"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=24
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=24
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
VARIANT="Workstation Edition"
VARIANT_ID=workstation
[fale@redhat 00_work_needed]$ uname -a
Linux redhat.com 4.6.7-300.fc24.x86_64 #1 SMP Wed Aug 17 18:48:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
````

**Comment by mattharrison** [comment]
Weird. It doesn't say that it can't open the file, it says it can't identify the file. Is the png a valid image? I can't replicate this. It works for me with both python 2 and 3.

**Comment by Fale** [comment]
Probably wget had some problem and did not notified it :/. Redownloading the image it works :)
